# Generated by Django 6.0.7 on 2026-07-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_profile_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resume_file',
        ),
    ]
