# Generated by Django 6.0.7 on 2026-07-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_job_expiry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_new_applicant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_weekly_report',
            field=models.BooleanField(default=True),
        ),
    ]
