# Generated by Django 6.0.7 on 2026-07-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
