# Generated by Django 6.0.7 on 2026-07-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-1 Years', '0-1 Years'), ('1-2 Years', '1-2 Years'), ('3-5 Years', '3-5 Years')], max_length=30),
        ),
    ]
